export const google = {
    headerRowNumber: 1,
    headerRow: [
        "Row Type",
        "Action",
        "Ad status",
        "Final URL",
        "Beacon URLs",
        "Headline 1",
        "Headline 1 position",
        "Headline 2",
        "Headline 2 position",
        "Headline 3",
        "Headline 3 position",
        "Headline 4",
        "Headline 4 position",
        "Headline 5",
        "Headline 5 position",
        "Headline 6",
        "Headline 6 position",
        "Headline 7",
        "Headline 7 position",
        "Headline 8",
        "Headline 8 position",
        "Headline 9",
        "Headline 9 position",
        "Headline 10",
        "Headline 10 position",
        "Headline 11",
        "Headline 11 position",
        "Headline 12",
        "Headline 12 position",
        "Headline 13",
        "Headline 13 position",
        "Headline 14",
        "Headline 14 position",
        "Headline 15",
        "Headline 15 position",
        "Description",
        "Description 1",
        "Description 1 position",
        "Description 2",
        "Description 2 position",
        "Description 3",
        "Description 3 position",
        "Description 4",
        "Description 4 position",
        "Ad name",
        "ad.device_preference",
        "ad.display_url",
        "Path 1",
        "Path 2",
        "Auto-applied ad suggestion",
        "Mobile final URL",
        "Tracking template",
        "Final URL suffix",
        "Custom parameter",
        "Campaign",
        "Ad group",
        "Status",
        "Status reasons",
        "Ad type",
        "Impr.",
        "Interactions",
        "Interaction rate",
        "Currency code",
        "Avg. cost",
        "Cost",
        "Conv. rate",
        "Conversions",
        "Cost / conv.",
        "Customer ID",
        "Campaign Id",
        "Ad group ID",
        "Ad ID",
        "Campaign type"
    ]
}